WIP: Store ghc version for each snippet
haskell/play-haskell pull request #24
Opened 2023-03-01 18:02 UTC by trevorsibanda

## Proposed changes

- Move Contents out of DB and rename to Paste
- Add ghcVersion field to Paste
- Alter paste table to include ghcVersion column
- Modify play.mustache and play-index.ts
- Add db migration script

## Contributor checklist

- [ x] My PR is related to #15, if applicable
- [x ] I have read and understood the [CONTRIBUTING guide](https://github.com/tomsmeding/play-haskell/blob/master/CONTRIBUTING.md)

2023-03-02 12:44 UTC, tomsmeding commented
Something that I thought of (not sure if this is still applicable after your last commit): I'm not sure I'd like the string "default" to ever appear in a `Version`. This is kind of in-band signalling of an unusual value, which I usually prefer to model using an ADT, i.e. `Maybe Version` in this case. In the database, the same idea would apply by making the `ghcVersion` column nullable, and storing `NULL` whenever there is no version specified.

2023-03-03 09:07 UTC, trevorsibanda commented
I've made the ghcVersion column nullable and left it empty if it's not a supported version.

2023-03-04 00:15 UTC, piotr-lewandowski commented on play-haskell-server/src/DB.hs
> +  toField (Version v)= toField v
Please
```suggestion
  toField (Version v) = toField v
```

2023-03-17 07:53 UTC, tomsmeding commented
Oh oops -- apparently I do not get notifications of PRs being set to "ready for review", and I'd missed most of what happened here completely. Sorry for the silence.

I'll try to review this either today or early next week.

2023-03-17 20:19 UTC, tomsmeding requested changes
Disclaimer: I didn't test yet! Just looked at the code in the PR here.

Mostly looks good, couple of small things. Perhaps you can have a look at those? If you have no time any more I can also address them if you want.

2023-03-17 20:19 UTC, tomsmeding commented on play-haskell-server/src/Pages.hs
> +  Just ( Version v) -> toMustache v
Superfluous space after `(`.
Also, `versionToMustache = mixinMaybeNull (\(Version v) -> v)` if I'm not mistaken.

2025-01-30 18:12 UTC, tomsmeding commented
I've implemented this functionality in https://github.com/haskell/play-haskell/compare/7eace73a6f7c4f2454a91b0afaf863e302167b8d...3df191ff71a3c2f7775e7ed81b572e2edd47e8a6.

2025-01-30 18:12 UTC, closed without merging